@testset "Low-resource modeling plan report contract" begin
    package_root = normpath(joinpath(@__DIR__, ".."))
    report_path = joinpath(package_root, "outputs", "reports", "a2780_low_resource_modeling_plan.html")
    docs_report_path = normpath(joinpath(package_root, "..", "..", "docs", "Modeling_Approaches", "02_mechanical_automatic_package", "outputs", "reports", "a2780_low_resource_modeling_plan.html"))

    @test isfile(report_path)
    @test isfile(docs_report_path)
    report = read(report_path, String)
    @test report == read(docs_report_path, String)
    @test occursin("A2780 Low-Resource Modeling Plan", report)
    @test occursin("Untreated Monoculture", report)
    @test occursin("Treated Monoculture", report)
    @test occursin("Untreated Coculture", report)
    @test occursin("Treated Coculture", report)
    @test occursin("Low-Resource Treated Monoculture", report)
    @test occursin("Low-Resource Coculture", report)
    @test occursin("Low-Resource Treated Coculture", report)
    @test occursin("Growth-Rate And Carrying-Capacity Modifiers", report)
    @test occursin("Separately Fitted Growth Rate", report)
    @test occursin("\\rho_r r_X", report)
    @test occursin("\\rho_KK_X", report)
    @test occursin("r_X^{LR}", report)
    @test occursin("A_X(t)=1-e^{-\\lambda_X t}", report)
    @test occursin("rises continuously from zero", report)
    @test !occursin("t_{on,X}", report)
    @test !occursin("\\begin{cases}", report)
    @test occursin("\\beta_XA_X(t)H_X(D)X", report)
    @test occursin("Drug Effect Distributed Into Logistic Growth", report)
    @test occursin("Normal logistic form", report)
    @test occursin("Normal logistic without Hill saturation", report)
    @test occursin("r_X\\,X\\left(1-\\frac{X}{K_X}\\right)-\\beta_X", report)
    @test occursin("\\frac{r_X}{K_X}X^2", report)
    @test occursin("\\beta_X\\,A_X(t)\\,D\\,X", report)
    @test !occursin("\\frac{dE}{dt}", report)
    @test !occursin("\\frac{dZ}{dt}", report)
    @test !occursin("drug-disappearance", lowercase(report))
    @test occursin("optional stage", report)
    @test occursin("<h3>Notation</h3>", report)
    @test !occursin("Focused Sources", report)
    @test !occursin("Fitting And Decision Plan", report)
    @test !occursin("class=\"status", report)
    @test !occursin("Surface-limited von Bertalanffy", report)
    @test !occursin("\\gamma_R", report)
    @test !occursin("q_N(E)", report)
end
