@testset "Adaptive simulator report contract" begin
    package_root = normpath(joinpath(@__DIR__, ".."))
    report_path = joinpath(package_root, "outputs", "reports", "a2780_adaptive_treatment_simulations.html")
    config_path = joinpath(package_root, "outputs", "reports", "a2780_adaptive_simulator_config.js")
    report = read(report_path, String)

    @test isfile(config_path)
    @test occursin("a2780_adaptive_simulator_config.js", report)
    @test occursin("&larr; Back", report)
    @test !occursin("Back to reports", report)
    @test !occursin("Research and teaching use only", report)
    @test !occursin("A2780 research simulator", report)
    @test !occursin("Explore fitted growth and treatment schedules", report)
    @test occursin("id=\"advancedModelSelect\"", report)
    @test occursin("id=\"showLatent\"", report)
    @test occursin("id=\"addInterval\"", report)
    @test occursin("data-interval-field=\"dose\"", report)
    @test occursin("data-interval-field=\"refresh\"", report)
    @test occursin("function updateCustomInterval", report)
    @test occursin("Default dose for new windows", report)
    @test occursin("Treatment windows cannot overlap", report)
    @test occursin("80% scenario ensemble after day 14", report)
    @test occursin("table-scroll", report)
    @test occursin("doseToEffect", report)
    @test occursin("function rankedCandidates(stage", report)
    @test occursin("const stage1Candidates =", report)
    @test occursin("const stage2Candidates =", report)
    @test occursin("const stage3Candidates =", report)
    @test occursin("const stage4Candidates =", report)
    @test occursin(".slice(0, 5)", report)
    @test occursin("function candidateKey(candidate)", report)
    @test occursin("let selectedStage1Candidates", report)
    @test occursin("let selectedStage2Candidate", report)
    @test occursin("let selectedStage3Candidate", report)
    @test occursin("let selectedStage4Candidate = defaultStage4Candidate", report)
    @test occursin("const treatment = selectedStage4Candidate.parameters", report)
    @test occursin("const interaction = selectedStage3Candidate.parameters", report)
    @test occursin("selectedStage1Candidates.A2780Naive.baselines", report)
    @test occursin("beta_cis_sensitive ?? treatment.beta_cis", report)
    @test occursin("beta_cis_tolerant ?? treatment.beta_cis", report)
    @test occursin("id=\"stage1NaiveSelect\"", report)
    @test occursin("id=\"stage1CisSelect\"", report)
    @test occursin("id=\"stage2ModelSelect\"", report)
    @test occursin("id=\"stage3ModelSelect\"", report)
    @test occursin("Any combination other than the original winners is a counterfactual composition", report)
    @test occursin("coculture_treated__20k__50-50__1", report)
    @test occursin("value=\"fittedTreatment\"", report)
    @test occursin("buildExperimentDefaults", report)
    @test occursin("Reset to selected experiment", report)
    @test occursin("initialTotal\" type=\"range\" min=\"1\"", report)
    @test occursin("id=\"initialTotalValue\" type=\"number\"", report)
    @test occursin("id=\"cisFractionValue\" type=\"number\"", report)
    @test occursin("function bindExactInput", report)
    @test occursin("bindExactInput(\"cisFractionValue\", \"cisFraction\", value => value / 100)", report)
    @test occursin("both lineages always total 100%", report)
    @test occursin("schedule: lib.treated ? \"fittedTreatment\" : \"none\"", report)
    @test occursin("if (schedule === \"fittedTreatment\")", report)
    @test occursin("if (schedule === \"originalRefresh\")", report)
    @test occursin("return p.maxDose;", report)
    @test occursin("const deathN = isCoculture ? p.deathN : 0", report)
    @test occursin("adaptiveConfig.experimental_library", report)
    @test occursin("visibleSchedules.map(schedule => simulate(schedule))", report)
    @test !occursin("visibleSchedules.map(simulate)", report)
    @test occursin("function stepRK4", report)
    @test occursin("const canSchedule = lib.culture === \"coculture\"", report)
    @test occursin("function libraryChoices(category)", report)
    @test !occursin("Math.max(100, Math.min(100000", report)
end
