@testset "Low-resource modeling plan report contract" begin
    package_root = normpath(joinpath(@__DIR__, ".."))
    report_path = joinpath(package_root, "outputs", "reports", "a2780_low_resource_modeling_plan.html")
    docs_report_path = normpath(joinpath(package_root, "..", "..", "docs", "Modeling_Approaches", "02_mechanical_automatic_package", "outputs", "reports", "a2780_low_resource_modeling_plan.html"))

    @test isfile(report_path)
    @test isfile(docs_report_path)
    report = read(report_path, String)
    section_html(id) = begin
        matched = match(Regex("<section id=\"" * id * "\">([\\s\\S]*?)</section>"), report)
        matched === nothing ? "" : matched.captures[1]
    end
    @test report == read(docs_report_path, String)
    @test occursin("A2780 Low-Resource Modeling Plan", report)
    @test occursin("Untreated Monoculture", report)
    @test occursin("Treated Monoculture", report)
    @test occursin("Untreated Coculture", report)
    @test occursin("Treated Coculture", report)
    @test occursin("Low-Resource Treated Monoculture", report)
    @test occursin("Low-Resource Coculture", report)
    @test occursin("Low-Resource Treated Coculture", report)
    @test occursin("Growth-Rate And Carrying-Capacity Modifiers", report)
    @test occursin("Separately Fitted Growth Rate", report)
    @test occursin("Lineage-Specific Subtractive Loss", report)
    @test occursin("u_R(t)=\\frac{10-F(t)}{10-0.05}", report)
    @test occursin("0.05\\le F(t)\\le 10", report)
    @test count("d_N^{LR}u_R(t)N", report) == 4
    @test count("d_C^{LR}u_R(t)C", report) == 4
    @test occursin("0 at 10% FBS and 1 at 0.05% FBS", report)
    @test occursin("A2780Naive monoculture", report)
    @test occursin("A2780cis-resistant monoculture", report)
    @test count("^{\\theta_X}", report) == 1
    @test !occursin("^{\\theta_N}", report)
    @test !occursin("^{\\theta_C}", report)
    @test occursin("r_NN\\left(1-\\frac{N+\\alpha_{NC}C}{K}\\right)", report)
    @test occursin("r_CC\\left(1-\\frac{C+\\alpha_{CN}N}{K}\\right)", report)
    @test count("\\frac{N+\\alpha_{NC}C}{K}", report) == 5
    @test count("\\frac{C+\\alpha_{CN}N}{K}", report) == 5
    @test !occursin("\\frac{N+\\alpha_{NC}C}{K_N}", report)
    @test !occursin("\\frac{C+\\alpha_{CN}N}{K_C}", report)
    @test occursin("Given carrying capacity shared by both lineages in coculture", report)

    treated_coculture = section_html("treated-coculture")
    @test !occursin("-d_NN", treated_coculture)
    @test !occursin("-d_CC", treated_coculture)
    @test occursin("ordinary coculture death terms are not carried forward", treated_coculture)

    for section_id in ("low-resource-treated-monoculture", "low-resource-coculture", "low-resource-treated-coculture")
        downstream = section_html(section_id)
        @test occursin("d_N^{LR}", downstream)
        @test occursin("d_C^{LR}", downstream)
        @test occursin("u_R(t)", downstream)
        @test !occursin("\\rho_r", downstream)
        @test !occursin("\\rho_K", downstream)
        @test !occursin("r_X^{LR}", downstream)
        @test !occursin("-d_NN", downstream)
        @test !occursin("-d_CC", downstream)
    end
    @test occursin("\\rho_r r_X", report)
    @test occursin("\\rho_KK_X", report)
    @test occursin("r_X^{LR}", report)
    @test occursin("A_X(t)=1-e^{-\\lambda_X t}", report)
    @test occursin("rises continuously from zero", report)
    @test !occursin("t_{on,X}", report)
    @test !occursin("\\begin{cases}", report)
    @test occursin("\\beta_XA_X(t)H_X(D)X", report)
    @test occursin("Drug Effect Distributed Into Logistic Growth", report)
    @test occursin("Normal logistic form", report)
    @test occursin("Normal logistic without Hill saturation", report)
    @test occursin("r_X\\,X\\left(1-\\frac{X}{K_X}\\right)-\\beta_X", report)
    @test occursin("\\frac{r_X}{K_X}X^2", report)
    @test occursin("\\beta_X\\,A_X(t)\\,D\\,X", report)
    @test !occursin("\\frac{dE}{dt}", report)
    @test !occursin("\\frac{dZ}{dt}", report)
    @test !occursin("drug-disappearance", lowercase(report))
    @test occursin("optional stage", report)
    @test occursin("Logistic <span aria-label=\"carried forward\">&#9733;</span>", report)
    @test occursin("Time-Delayed Hill Function <span aria-label=\"carried forward\">&#9733;</span>", report)
    @test occursin("Asymmetric Crowding <span aria-label=\"carried forward\">&#9733;</span>", report)
    @test occursin("Lineage-Specific Subtractive Loss <span aria-label=\"carried forward\">&#9733;</span>", report)
    @test occursin("<h3>Notation</h3>", report)
    @test !occursin("Focused Sources", report)
    @test !occursin("Fitting And Decision Plan", report)
    @test !occursin("class=\"status", report)
    @test !occursin("Surface-limited von Bertalanffy", report)
    @test !occursin("\\gamma_R", report)
    @test !occursin("q_N(E)", report)
end
