@testset "Adaptive simulator report contract" begin
    package_root = normpath(joinpath(@__DIR__, ".."))
    report_path = joinpath(package_root, "outputs", "reports", "a2780_adaptive_treatment_simulations.html")
    config_path = joinpath(package_root, "outputs", "reports", "a2780_adaptive_simulator_config.js")
    report = read(report_path, String)

    @test isfile(config_path)
    @test occursin("a2780_adaptive_simulator_config.js", report)
    @test occursin("id=\"advancedModelSelect\"", report)
    @test occursin("id=\"showLatent\"", report)
    @test occursin("id=\"addInterval\"", report)
    @test occursin("id=\"cancelInterval\"", report)
    @test occursin("data-edit-interval", report)
    @test occursin("beginIntervalEdit", report)
    @test occursin("index !== editingIntervalIndex", report)
    @test occursin("Active windows cannot overlap", report)
    @test occursin("80% scenario ensemble after day 14", report)
    @test occursin("table-scroll", report)
    @test occursin("doseToEffect", report)
    @test occursin("selectedAdvancedModel = adaptiveConfig.winners.stage4.model", report)
    @test occursin("coculture_treated__20k__50-50__1", report)
    @test occursin("value=\"fittedTreatment\"", report)
    @test occursin("buildExperimentDefaults", report)
    @test occursin("Reset to selected experiment", report)
    @test occursin("initialTotal\" type=\"range\" min=\"1\"", report)
    @test occursin("schedule: lib.treated ? \"fittedTreatment\" : \"none\"", report)
    @test occursin("if (schedule === \"fittedTreatment\")", report)
    @test occursin("if (schedule === \"originalRefresh\")", report)
    @test occursin("return p.maxDose;", report)
    @test occursin("const deathN = isCoculture ? p.deathN : 0", report)
    @test occursin("adaptiveConfig.experimental_library", report)
    @test occursin("visibleSchedules.map(schedule => simulate(schedule))", report)
    @test !occursin("visibleSchedules.map(simulate)", report)
    @test occursin("function stepRK4", report)
    @test occursin("const canSchedule = lib.culture === \"coculture\"", report)
    @test occursin("function libraryChoices(category)", report)
    @test !occursin("Math.max(100, Math.min(100000", report)
end
